### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by clecio81** [ErezAmihud/dearmor#14]
Traceback (most recent call last):
  File "/usr/local/bin/dearmor", line 8, in <module>
    sys.exit(main_cli())
  File "/usr/local/lib/python3.8/dist-packages/dearmor/__main__.py", line 51, in main_cli
    dearmor_main(parser.parse_args().file)
  File "/usr/local/lib/python3.8/dist-packages/dearmor/__main__.py", line 32, in dearmor_main
    inject(child[0].pid, str(Path(__file__).parent / "Release" / "dearmor.dll"))
IndexError: list index out of range

**Comment by ErezAmihud** [comment]
Linux is not supported, the error is because deaemor failed to launch you program with `python <your py file>`

I don't actively work on it anymore, so there will be no linux support unless someone opens a merge request
