### ISSUE TITLE
problem with dearmor executable

### ISSUE THREAD

**Issue by Sa1tama228** [ErezAmihud/dearmor#18]
here is error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Scripts\dearmor.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor\__main__.py", line 51, in main_cli
    dearmor_main(parser.parse_args().file)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor\__main__.py", line 20, in dearmor_main
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 не является приложением Win32 (Translate: is not Win32)
 ```

**Comment by Sa1tama228** [comment]
btw the soft that i wanted deobfuscate written in python 3.8 if its important

**Comment by ErezAmihud** [comment]
What is the command line you run?

**Comment by Sa1tama228** [comment]
> What is the command line you run?

just with flag -i, i tried to run it with cmd, ps and pycharm terminal

**Comment by ErezAmihud** [comment]
> > What is the command line you run?
> 
> just with flag -i, i tried to run it with cmd, ps and pycharm terminal

What did you write in the terminal...

**Comment by Sa1tama228** [comment]
> > > What is the command line you run?
> > 
> > 
> > just with flag -i, i tried to run it with cmd, ps and pycharm terminal
> 
> What did you write in the terminal...

dearmor -i main.pyc...

**Comment by ErezAmihud** [comment]
> > > > What is the command line you run?
> > > 
> > > 
> > > just with flag -i, i tried to run it with cmd, ps and pycharm terminal
> > 
> > 
> > What did you write in the terminal...
> 
> dearmor -i main.pyc...

Ok so the problem is you tried to run it with pyc and not with py file. To run pyc file you have to have the exact same 0ython version and in the `__main__.py` file in this repo it is not really supported.
Instead, decompile the pyc to py and then run dearmor

**Comment by Sa1tama228** [comment]
ty, ill try and report if smth is wrong

**Comment by Sa1tama228** [comment]
now there is something with the pid

`Traceback (most recent call last):
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil\_pswindows.py", line 727, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil\_pswindows.py", line 989, in create_time
    _user, _system, created = cext.proc_times(self.pid)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil\__init__.py", line 355, in _init
    self.create_time()
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil\__init__.py", line 757, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil\_pswindows.py", line 729, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: process no longer exists (pid=5568)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Scripts\dearmor.exe\__main__.py", line 7, in <module>
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor\__main__.py", line 51, in main_cli
    dearmor_main(parser.parse_args().file)
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor\__main__.py", line 30, in dearmor_main
    current_process = psutil.Process(p.pid)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil\__init__.py", line 319, in __init__
    self._init(pid)
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil\__init__.py", line 368, in _init
    raise NoSuchProcess(pid, msg=msg)
psutil.NoSuchProcess: process PID not found (pid=5568)`

**Comment by ErezAmihud** [comment]
> now there is something with the pid
> 
> `Traceback (most recent call last): File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil_pswindows.py", line 727, in wrapper return fun(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil_pswindows.py", line 989, in create_time _user, _system, created = cext.proc_times(self.pid) ^^^^^^^^^^^^^^^^^^^^^^^^^ ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 355, in _init self.create_time() File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 757, in create_time self._create_time = self._proc.create_time() ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil_pswindows.py", line 729, in wrapper raise convert_oserror(err, pid=self.pid, name=self._name) psutil.NoSuchProcess: process no longer exists (pid=5568)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Scripts\dearmor.exe__main__.py", line 7, in File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor__main__.py", line 51, in main_cli dearmor_main(parser.parse_args().file) File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor__main__.py", line 30, in dearmor_main current_process = psutil.Process(p.pid) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 319, in **init** self._init(pid) File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 368, in _init raise NoSuchProcess(pid, msg=msg) psutil.NoSuchProcess: process PID not found (pid=5568)`

The python program should run atleast a few seconds - otherwise there is a race condition between the process creation and the attach that happens.
You can clone the repo and change the sleep or remove it to try to do it.

**Comment by Sa1tama228** [comment]
> > now there is something with the pid
> > `Traceback (most recent call last): File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil_pswindows.py", line 727, in wrapper return fun(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil_pswindows.py", line 989, in create_time _user, _system, created = cext.proc_times(self.pid) ^^^^^^^^^^^^^^^^^^^^^^^^^ ProcessLookupError: [Errno 3] assume no such process (originated from GetExitCodeProcess != STILL_ACTIVE)
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 355, in _init self.create_time() File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 757, in create_time self._create_time = self._proc.create_time() ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil_pswindows.py", line 729, in wrapper raise convert_oserror(err, pid=self.pid, name=self._name) psutil.NoSuchProcess: process no longer exists (pid=5568)
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Scripts\dearmor.exe__main__.py", line 7, in File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor__main__.py", line 51, in main_cli dearmor_main(parser.parse_args().file) File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\dearmor__main__.py", line 30, in dearmor_main current_process = psutil.Process(p.pid) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 319, in **init** self._init(pid) File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\site-packages\psutil__init__.py", line 368, in _init raise NoSuchProcess(pid, msg=msg) psutil.NoSuchProcess: process PID not found (pid=5568)`
> 
> The python program should run atleast a few seconds - otherwise there is a race condition between the process creation and the attach that happens. You can clone the repo and change the sleep or remove it to try to do it.

and this is the problem, i extracted program with puinstxtractor, and after that the extracted version won't loads properly, it says that:  bad magic number in 'pytransform': b'U\r\r\n'
