### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Zoomer153** [ErezAmihud/dearmor#19]
C:\Tools\Reverse Tools\Reverse Static\Python\pyinstxtractor\eyedown.exe_extracted>dearmor -i script.py
Traceback (most recent call last):
  File "c:\users\john\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\john\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\John\AppData\Local\Programs\Python\Python38\Scripts\dearmor.exe\__main__.py", line 7, in <module>
  File "c:\users\john\appdata\local\programs\python\python38\lib\site-packages\dearmor\__main__.py", line 51, in main_cli
    dearmor_main(parser.parse_args().file)
  File "c:\users\john\appdata\local\programs\python\python38\lib\site-packages\dearmor\__main__.py", line 32, in dearmor_main
    inject(child[0].pid, str(Path(__file__).parent / "Release" / "dearmor.dll"))
IndexError: list index out of range

I tried on an executable or on py, but nothing changes

**Comment by ErezAmihud** [comment]
It means the process died before the dll could be injected to it. If you know of a way to make it live longer before dying, do it, and I think there is a `sleep` order in dearmor, so also remove it.
