### ISSUE TITLE
dearmor.dll is missing. No proper guide in the README..

### ISSUE THREAD

**Issue by 59n** [ErezAmihud/dearmor#9]
Simply all I did was:
pip install dearmor
Then went to test on my EXE:
dearmor -i main.exe
Got the error:
`Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\Scripts\dearmor.exe\__main__.py", line 7, in <module>
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\dearmor\__main__.py", line 32, in main_cli
    dearmor_main(parser.parse_args().file)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\dearmor\__main__.py", line 21, in dearmor_main
    inject(child[0].pid, str(Path(__file__).parent /  "Release" / "dearmor.dll"))
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinjector\pyinjector.py", line 100, in inject
    raise LibraryNotFoundException(library_path)
pyinjector.pyinjector.LibraryNotFoundException: Could not find library: C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\dearmor\Release\dearmor.dll`

I have VS 2022 installed and CMake if it's even needed, no idea since it doesn't say that in the README just seen people talking about it in issues.
Please make it more clear how to use this..

**Comment by ErezAmihud** [comment]
Thank you for reporting, something probably went wrong when I uploaded the package to pypi, I will fix it in the next few days.

**Comment by ErezAmihud** [comment]
@59n It should be fixed now. Download version 0.3.1

Note that I was wrong earlier, you do must decompile the exe into regular encrypted pyarmor file. The dearmor package run `python <your-input>`, attaches to that process and decrypt.
